{
 "title": "New dashboard12",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Failed Request",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{application=\"MYAPPNAME\", status=\"500\"})",
     "legendFormat": "Failed Requests"
    }
   ]
  },
  {
   "title": "Blocked Thread",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_states_threads{application=\"MYAPPNAME\",state=\"blocked\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_threads_states_threads{application=\"MYAPPNAME\",state=\"waiting\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_usage{application=\"MYAPPNAME\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 7, "x": 9, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"MYAPPNAME\",area=\"heap\",id=\"G1 Eden Space\"}",
     "legendFormat": "G1 Eden Space"
    },
    {
     "expr": "jvm_memory_used_bytes{application=\"MYAPPNAME\",area=\"heap\",id=\"G1 Old Gen\"}",
     "legendFormat": "G1 Old Gen"
    },
    {
     "expr": "jvm_memory_used_bytes{application=\"MYAPPNAME\",area=\"heap\",id=\"G1 Survivor Space\"}",
     "legendFormat": "G1 Survivor Space"
    },
    {
     "expr": "jvm_memory_used_bytes{application=\"MYAPPNAME\",area=\"nonheap\",id=\"CodeHeap 'non-nmethods'\"}",
     "legendFormat": "CodeHeap 'non-nmethods'"
    },
    {
     "expr": "jvm_memory_used_bytes{application=\"MYAPPNAME\",area=\"nonheap\",id=\"CodeHeap 'non-profiled nmethods'\"}",
     "legendFormat": "CodeHeap 'non-profiled nmethods'"
    },
    {
     "expr": "jvm_memory_used_bytes{application=\"MYAPPNAME\",area=\"nonheap\",id=\"CodeHeap 'profiled nmethods'\"}",
     "legendFormat": "CodeHeap 'profiled nmethods'"
    },
    {
     "expr": "jvm_memory_used_bytes{application=\"MYAPPNAME\",area=\"nonheap\",id=\"Compressed Class Space\"}",
     "legendFormat": "Compressed Class Space"
    },
    {
     "expr": "jvm_memory_used_bytes{application=\"MYAPPNAME\",area=\"nonheap\",id=\"Metaspace\"}",
     "legendFormat": "Metaspace"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "logback_events_total{application=\"MYAPPNAME\"}",
     "legendFormat": "{{level}}"
    }
   ]
  }
 ]
}