global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'zipkin'
    static_configs:
      - targets: ['zipkin:9411']
    metrics_path: '/actuator/prometheus'  # Update to the correct path if needed

  - job_name: 'spring-boot-app'
    metrics_path: '/admin/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['host.docker.internal:9001']